<a href="https://colab.research.google.com/github/SineNitish/Spam_Detection_ML/blob/main/Spam_Detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Spam Detection 

Importing data 

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
df.groupby('Category').describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [ ]:
df['spam']=df['Category'].apply(lambda x: 1 if x=='spam' else 0)
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

Spliting the data into test and train

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.Message,df.spam)
X_train

4453    I've told you everything will stop. Just dont ...
497     Nope... Think i will go for it on monday... So...
2192    Thankyou so much for the call. I appreciate yo...
2109    FREE2DAY sexy St George's Day pic of Jordan!Tx...
2130           Mine here like all fr china then so noisy.
                              ...                        
3279                          What happened in interview?
1303    FRAN I DECIDED 2 GO N E WAY IM COMPLETELY BROK...
769     I cant pick the phone right now. Pls send a me...
459     1.20 that call cost. Which i guess isnt bad. M...
1213    Yo, the game almost over? Want to go to walmar...
Name: Message, Length: 4179, dtype: object

Applying Naive Bayes Model on CountVectorizer 

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
X_train_count = v.fit_transform(X_train.values)
X_train_count.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_count,y_train)

MultinomialNB()

In [ ]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]
emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])

In [ ]:
X_test_count = v.transform(X_test)
model.score(X_test_count, y_test)

0.9820531227566404

In [ ]:
Applying Naive Bayes Model on Tfidf

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
v = TfidfVectorizer()
X_train_count = v.fit_transform(X_train.values)
X_train_count.toarray()
print(v.idf_)

[7.03548143 6.39362755 8.64491934 ... 8.64491934 8.64491934 8.64491934]


In [ ]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_count,y_train)

MultinomialNB()

In [ ]:
X_test_count = v.transform(X_test)
model.score(X_test_count, y_test)

0.9576453697056713

Applying Naive Bayes Model on OneHotEncoder

In [ ]:
import sklearn.preprocessing as preprocessing
labelEnc = preprocessing.LabelEncoder()
new_target = labelEnc.fit_transform(X_train.values)
onehotEnc = preprocessing.OneHotEncoder()
X_train_count=onehotEnc.fit(new_target.reshape(-1, 1))
X_train_count

OneHotEncoder()

In [ ]:
X_test_count = v.transform(X_test)
model.score(X_test_count, y_test)

0.9576453697056713